// Pattern Matching Tests
// Testcases were partially created by Lily Val Richter, but were mostly taken from the sources listed below
// The copied testcases were copied in a different syntax and partially modified
// Licenses of these testcase-sources are reprinted below
//
// Sources for Testcases:
// 1. DotNet Runtime's AT&T Regex Tests: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/AttRegexTests.cs
// 2. D-lang's Regex Tests, which were in turn adapted from Henry Spencer's regex test code: https://github.com/dlang/phobos/blob/master/std/regex/internal/tests.d
//
// Other Testsuites that could be incorporated someday:
// - https://github.com/unicode-org/icu/blob/main/icu4c/source/test/testdata/regextst.txt
// - https://github.com/unicode-org/icu/blob/main/icu4c/source/test/testdata/regextst.txt
//
// Licenses:
// 1. MIT License via .NET Foundation Licenses
/*
 *	Glenn Fowler <gsf@research.att.com>
 *	AT&T Research
 *
 * PLEASE: publish your tests so everyone can benefit
 *
 * The following license covers testregex.c and all associated test data.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of THIS SOFTWARE FILE (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following disclaimer:
 *
 * THIS SOFTWARE IS PROVIDED BY AT&T ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL AT&T BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
// Tests sourced from .dat files at http://gsf.cococlyde.org/download.
// Then some inputs were deleted / tweaked based on expected differences in behavior.
//
// 2.  D-lang's Boost Software License and Henry Spencer's Copyright Notice for the original test-cases
/* Copyright (c) 1986 by University of Toronto.
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *
 * Written by Henry Spencer.  Not derived from licensed software.
 *
 * Permission is granted to anyone to use this software for any
 * purpose on any computer system, and to redistribute it freely,
 * subject to the following restrictions:
 *
 * 1. The author is not responsible for the consequences of use of
 *    this software, no matter how awful, even if they arise
 *    from defects in it.
 *
 * 2. The origin of this software must not be misrepresented, either
 *    by explicit claim or by omission.
 *
 * 3. Altered versions must be plainly marked as such, and must not
 *    be misrepresented as being the original software.
 */


#include "../src/base/ail_str.h"
#include "../src/pm/ail_pm.h"
#include "./assert.h"

typedef struct SuccTest {
    AIL_Str pattern;
    AIL_Str testStr;
    AIL_PM_Match greedyRes;
    AIL_PM_Match lazyRes;
} SuccTest;

typedef struct FailTest {
    AIL_Str pattern;
    AIL_PM_Err err;
} FailTest;

#define STR(lit) ail_str8_from_lit(lit)
#define SVS_TO_MATCH(pre, match) { .idx = (pre), .len = (match) }
#define _RES_3(pre, matched, post) SVS_TO_MATCH(sizeof(AIL_STRINGIFY(pre))-1, sizeof(AIL_STRINGIFY(matched))-1)
#define _RES_2(pre, matched)       _RES_3(pre, matched, "")
#define _RES_1(pre)                _RES_2(pre, "")
#define _RES_0()                   _RES_1("")
#define RES(...) AIL_VFUNC(_RES_, __VA_ARGS__)
#define TWICE_RES(...) STR(AIL_STRINGIFY(AIL_CONCAT(__VA_ARGS__))), RES(__VA_ARGS__), RES(__VA_ARGS__)
#define FAIL(pattern, err, i) { STR(pattern), { .type = err, .idx = i } }

#define pm_match(i, l) { .idx = (i), .len = (l) }
#define pm_match_2idxs(i1, i2) pm_match(i1, (i2) - (i1))
#define pm_match_twice(i, l) pm_match(i, l), pm_match(i, l)
#define pm_match_twice_2idxs(i1, i2) pm_match_twice(i1, (i2) - (i1))

global SuccTest glob_succ_tests[] = {
    { STR("*.c"), STR("test.c"),   pm_match_twice(0, 6) },
    { STR("*.c"), STR("test.cpp"), pm_match_twice(0, 6) },
    { STR("*.c"), STR("test.cpp"), pm_match_twice(0, 6) },
};

global FailTest glob_fail_tests[] = {
    FAIL(".c\\", AIL_PM_ERR_INCOMPLETE_ESCAPE, 2),
};

global SuccTest regex_succ_basic_tests[] = {
    { STR("x*"),     STR("axx"),          pm_match_twice(1, 2) },
    { STR("x+"),     STR("axx"),          pm_match_twice(1, 2) },
    { STR("x"),      STR("aaa"),          pm_match_twice(0, 0) },
    { STR("a*"),     STR("xxx"),          pm_match_twice(0, 0) },
    { STR("x*"),     STR("xxxa"),         pm_match_twice(0, 3) },
    { STR("a+"),     STR("xxx"),          pm_match_twice(0, 0) },
    { STR("\\.c"),   STR("test.cpp"),     pm_match_twice(4, 2) },
    { STR("\\.c"),   STR("testc.hc"),     pm_match_twice(0, 0) },
    { STR("\\.c"),   STR("test.cpp.cpp"), pm_match_twice(4, 2) },
    { STR("\\.c$"),  STR("test.cpp.c"),   pm_match_twice(8, 2) },
    { STR("\\.c$"),  STR("test.cpp"),     pm_match_twice(0, 0) },
    { STR("a...b"),  STR("abababbb"),     pm_match_twice_2idxs(2,7) },
    { STR("XXXXXX"), STR("..XXXXXX"),     pm_match_twice_2idxs(2,8) },
    { STR("\\)"),    STR("()"),           pm_match_twice_2idxs(1,2) },
    { STR("a]"),     STR("a]a"),          pm_match_twice_2idxs(0,2) },
    { STR("}"),      STR("}"),            pm_match_twice_2idxs(0,1) },
    { STR("\\}"),    STR("}"),            pm_match_twice_2idxs(0,1) },
    { STR("\\]"),    STR("]"),            pm_match_twice_2idxs(0,1) },
    { STR("]"),      STR("]"),            pm_match_twice_2idxs(0,1) },
    { STR("{"),      STR("{"),            pm_match_twice_2idxs(0,1) },
    { STR("^a"),     STR("ax"),           pm_match_twice_2idxs(0,1) },
    { STR("\\^a"),   STR("a^a"),          pm_match_twice_2idxs(1,3) },
    { STR("a\\^"),   STR("a^"),           pm_match_twice_2idxs(0,2) },
    { STR("a$"),     STR("aa"),           pm_match_twice_2idxs(1,2) },
    { STR("a\\$"),   STR("a$"),           pm_match_twice_2idxs(0,2) },
    { STR("^$"),     STR(""),             pm_match_twice_2idxs(0,0) },
    { STR("\n"),     STR("\n"),           pm_match_twice_2idxs(0,1) },
    { STR("\na"),    STR("\na"),          pm_match_twice_2idxs(0,2) },
    { STR("xxx"),    STR("xxx"),          pm_match_twice_2idxs(0,3) },
    { STR(".*"),     STR("\x0001\x00ff"), pm_match_twice_2idxs(0,2) },
    { STR("^"),      STR(""),             pm_match_twice_2idxs(0,0) },
    { STR("$"),      STR(""),             pm_match_twice_2idxs(0,0) },
    { STR("^a$"),    STR("a"),            pm_match_twice_2idxs(0,1) },
    { STR("abc"),    STR("abc"),          pm_match_twice_2idxs(0,3) },
    { STR("abc"),    STR("xabcy"),        pm_match_twice_2idxs(1,4) },
    { STR("abc"),    STR("ababc"),        pm_match_twice_2idxs(2,5) },
    { STR("ab*c"),   STR("abc"),          pm_match_twice_2idxs(0,3) },
    { STR("ab*bc"),  STR("abc"),          pm_match_twice_2idxs(0,3) },
    { STR("ab*bc"),  STR("abbc"),         pm_match_twice_2idxs(0,4) },
    { STR("ab*bc"),  STR("abbbbc"),       pm_match_twice_2idxs(0,6) },
    { STR("ab+bc"),  STR("abbc"),         pm_match_twice_2idxs(0,4) },
    { STR("ab+bc"),  STR("abbbbc"),       pm_match_twice_2idxs(0,6) },
    { STR("^abc$"),  STR("abc"),          pm_match_twice_2idxs(0,3) },
    { STR("^abc"),   STR("abcc"),         pm_match_twice_2idxs(0,3) },
    { STR("abc$"),   STR("aabc"),         pm_match_twice_2idxs(1,4) },
    { STR("^"),      STR("abc"),          pm_match_twice_2idxs(0,0) },
    { STR("$"),      STR("abc"),          pm_match_twice_2idxs(3,3) },
    { STR("a.c"),    STR("abc"),          pm_match_twice_2idxs(0,3) },
    { STR("a.c"),    STR("axc"),          pm_match_twice_2idxs(0,3) },
    { STR("a.*c"),   STR("axyzc"),        pm_match_twice_2idxs(0,5) },
    { STR("a]"),     STR("a]"),           pm_match_twice_2idxs(0,2) },
    { STR("a\\(b"),  STR("a(b"),          pm_match_twice_2idxs(0,3) },
    { STR("a\\(*b"), STR("ab"),           pm_match_twice_2idxs(0,2) },
    { STR("a\\(*b"), STR("a((b"),         pm_match_twice_2idxs(0,4) },
    { STR("a*"),     STR(""),             pm_match_twice_2idxs(0,0) },
    { STR("ab*"),    STR("xabyabbbz"),    pm_match_twice_2idxs(1,3) },
    { STR("ab*"),    STR("xayabbbz"),     pm_match_twice_2idxs(1,2) },
    { STR("abcd"),   STR("abcd"),         pm_match_twice_2idxs(0,4) },
    { STR("^.+$"),   STR("vivi"),         pm_match_twice_2idxs(0,4) },
    { STR("\\\\XXX"),  STR("\\XXX"),      pm_match_twice_2idxs(0,4) },
    { STR("\\\\000"),  STR("\\000"),      pm_match_twice_2idxs(0,4) },
    { STR("abcd*efg"), STR("abcdefg"),    pm_match_twice_2idxs(0,7) },
    { STR("a*a*a*a*a*b"),    STR("aaaaaaaaab"),          pm_match_twice_2idxs(0,10) },
    { STR("abracadabra$"),   STR("abracadabracadabra"),  pm_match_twice_2idxs(7,18) },
    { STR("multiple words"), STR("multiple words yeah"), pm_match_twice_2idxs(0,14) },
    { STR("aaaa\nbbbb\ncccc\nddddd\neeeeee\nfffffff\ngggg\nhhhh\niiiii\njjjjj\nkkkkk\nllll"), STR("XaaaXbbbXcccXdddXeeeXfffXgggXhhhXiiiXjjjXkkkXlllXcbaXaaaa"), pm_match_twice_2idxs(0,0) },
};

global SuccTest regex_succ_question_tests[] = {
    { STR("ab?bc"), STR("abbc"), pm_match_twice_2idxs(0,4) },
    { STR("ab?bc"), STR("abc"),  pm_match_twice_2idxs(0,3) },
    { STR("ab?c"),  STR("abc"),  pm_match_twice_2idxs(0,3) },
};

global SuccTest regex_succ_group_tests[] = {
    // { STR("[a-m-]*"), STR("--amoma--"), pm_match_twice_2idxs(0,4) },
    { STR("[^a]"), STR("\n"), pm_match_twice_2idxs(0,1) },
    { STR("a[bc]d"), STR("abd"), pm_match_twice_2idxs(0,3) },
    { STR("a[b-d]e"), STR("ace"), pm_match_twice_2idxs(0,3) },
    { STR("a[b-d]"), STR("aac"), pm_match_twice_2idxs(1,3) },
    // { STR("a[-b]"), STR("a-"), pm_match_twice_2idxs(0,2) },
    // { STR("a[b-]"), STR("a-"), pm_match_twice_2idxs(0,2) },
    { STR("a[]]b"), STR("a]b"), pm_match_twice_2idxs(0,3) },
    // { STR("a[^bc]d"), STR("aed"), pm_match_twice_2idxs(0,3) },
    // { STR("a[^-b]c"), STR("adc"), pm_match_twice_2idxs(0,3) },
    // { STR("a[^]b]c"), STR("adc"), pm_match_twice_2idxs(0,3) },
    // { STR("[^ab]*"), STR("cde"), pm_match_twice_2idxs(0,3) },
    { STR("[abhgefdc]ij"), STR("hij"), pm_match_twice_2idxs(0,3) },
    { STR("a[bcd]*dcdcde"), STR("adcdcde"), pm_match_twice_2idxs(0,7) },
    { STR("[A-Za-z_][A-Za-z0-9_]*"), STR("alpha"), pm_match_twice_2idxs(0,5) },
    // { STR("[a-]*"), STR("--a"), pm_match_twice_2idxs(0,3) },
    // { STR("[^-]"), STR("--a"), pm_match_twice_2idxs(2,3) },
    // { STR("a[-]?c"), STR("ac"), pm_match_twice_2idxs(0,3) },
};

global SuccTest regex_succ_or_tests[] = {
    { STR("ab|abab"), STR("abbabab"), pm_match_twice_2idxs(0,2) },
    { STR("aba|bab|bba"), STR("baaabbbaba"), pm_match_twice_2idxs(5,8) },
    { STR("aba|bab"), STR("baaabbbaba"), pm_match_twice_2idxs(6,9) },
    { STR("ab|a"), STR("xabc"), pm_match_twice_2idxs(1,3) },
    { STR("ab|a"), STR("xxabc"), pm_match_twice_2idxs(2,4) },
    { STR(":::1:::0:|:::1:1:0:"), STR(":::0:::1:::1:::0:"), pm_match_twice_2idxs(8,17) },
    { STR(":::1:::0:|:::1:1:1:"), STR(":::0:::1:::1:::0:"), pm_match_twice_2idxs(8,17) },
    { STR("abaa|abbaa|abbbaa|abbbbaa"), STR("ababbabbbabbbabbbbabbbbaa"), pm_match_twice_2idxs(18,25) },
    { STR("abaa|abbaa|abbbaa|abbbbaa"), STR("ababbabbbabbbabbbbabaa"), pm_match_twice_2idxs(18,22) },
    { STR("aaac|aabc|abac|abbc|baac|babc|bbac|bbbc"), STR("baaabbbabac"), pm_match_twice_2idxs(7,11) },
    { STR("aaaa|bbbb|cccc|ddddd|eeeeee|fffffff|gggg|hhhh|iiiii|jjjjj|kkkkk|llll"), STR("XaaaXbbbXcccXdddXeeeXfffXgggXhhhXiiiXjjjXkkkXlllXcbaXaaaa"), pm_match_twice_2idxs(53,57) },
    { STR("ab|cd"), STR("abc"), pm_match_twice_2idxs(0,2) },
    { STR("ab|cd"), STR("abcd"), pm_match_twice_2idxs(0,2) },
    { STR("a|b|c|d|e"), STR("e"), pm_match_twice_2idxs(0,1) },
};

global SuccTest regex_succ_subexpr_tests[] = {
    { STR("a($)"), STR("aa"), pm_match_twice_2idxs(1,2) },
    { STR("(a.|.a.)*|(a|.a...)"), STR("aa"), pm_match_twice_2idxs(0,2) },
    { STR("a*(^a)"), STR("aa"), pm_match_twice_2idxs(0,1) },
    { STR("(..)*(...)*"), STR("a"), pm_match_twice_2idxs(0,0) },
    { STR("(..)*(...)*"), STR("abcd"), pm_match_twice_2idxs(0,4) },
    { STR("(aa|aaa)*|(a|aaaaa)"), STR("aa"), pm_match_twice_2idxs(0,2) },
    { STR("(ab|a)(bc|c)"), STR("abc"), pm_match_twice_2idxs(0,3) },
    { STR("(ab)c|abc"), STR("abc"), pm_match_twice_2idxs(0,3) },
    { STR(".*(/000).*"), STR("/000"), pm_match_twice_2idxs(0,4) },
    { STR(".*(\\\\000).*"), STR("\\000"), pm_match_twice_2idxs(0,4) },
    { STR("a{0}b"), STR("ab"), pm_match_twice_2idxs(1,2) },
    { STR("(a*)(b?)(b+)b{3}"), STR("aaabbbbbbb"), pm_match_2idxs(0,10), pm_match_2idxs(4,7) },
    { STR("(a*)(b{0,1})(b{1,})b{3}"), STR("aaabbbbbbb"), pm_match_2idxs(0,10), pm_match_2idxs(4,7) },
    { STR("((a|a)|a)"), STR("a"), pm_match_twice_2idxs(0,1) },
    { STR("(a*)(a|aa)"), STR("aaaa"), pm_match_2idxs(0,4), pm_match_2idxs(3,4) },
    { STR("a*(a.|aa)"), STR("aaaa"), pm_match_2idxs(0,4), pm_match_2idxs(2,4) },
    { STR("(a|b)?.*"), STR("b"), pm_match_twice_2idxs(0,1) },
    { STR("(a|b)c|a(b|c)"), STR("ac"), pm_match_twice_2idxs(0,2) },
    { STR("(a|b)*c|(a|ab)*c"), STR("abc"), pm_match_twice_2idxs(0,3) },
    { STR("(a|b)*c|(a|ab)*c"), STR("xc"), pm_match_twice_2idxs(1,2) },
    { STR("(.a|.b).*|.*(.a|.b)"), STR("xa"), pm_match_twice_2idxs(0,2) },
    { STR("a?(ab|ba)ab"), STR("abab"), pm_match_twice_2idxs(0,4) },
    { STR("a?(ac{0}b|ba)ab"), STR("abab"), pm_match_twice_2idxs(0,4) },
    { STR("(?i)(Ab|cD)*"), STR("aBcD"), pm_match_twice_2idxs(0,4) },
    { STR("(a)(b)(c)"), STR("abc"), pm_match_twice_2idxs(0,3) },
    { STR("(^|[ (,;])((([Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))([^0-9]|$)"), STR("feb 6,"), pm_match_twice_2idxs(0,6) },
    { STR("(^|[ (,;])((([Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))([^0-9]|$)"), STR("2/7"), pm_match_twice_2idxs(0,3) },
    { STR("(^|[ (,;])((([Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))([^0-9]|$)"), STR("feb 1,Feb 6"), pm_match_twice_2idxs(5,11) },
    { STR("((((((((((((((((((((((((((((((x))))))))))))))))))))))))))))))"), STR("x"), pm_match_twice_2idxs(0,1) },
    { STR("((((((((((((((((((((((((((((((x))))))))))))))))))))))))))))))*"), STR("xx"), pm_match_twice_2idxs(0,2) },
    { STR("a?(ab|ba)*"), STR("ababababababababababababababababababababababababababababababababababababababababa"), pm_match_2idxs(0,81), pm_match_2idxs(79,81) },
    { STR("((a))"), STR("abc"), pm_match_twice_2idxs(0,1) },
    { STR("(a)b(c)"), STR("abc"), pm_match_twice_2idxs(0,3) },
    { STR("a+b+c"), STR("aabbabc"), pm_match_twice_2idxs(4,7) },
    { STR("a*"), STR("aaa"), pm_match_twice_2idxs(0,3) },
    { STR("(a*)*"), STR("-"), pm_match_twice_2idxs(0,0) },
    { STR("(a*)+"), STR("-"), pm_match_twice_2idxs(0,0) },
    { STR("(a*|b)*"), STR("-"), pm_match_twice_2idxs(0,0) },
    { STR("(a+|b)*"), STR("ab"), pm_match_2idxs(0,2), pm_match_2idxs(1,2) },
    { STR("(a+|b)+"), STR("ab"), pm_match_2idxs(0,2), pm_match_2idxs(1,2) },
    { STR("(a+|b)?"), STR("ab"), pm_match_2idxs(0,1), pm_match_2idxs(0,1) },
    { STR("(^)*"), STR("-"), pm_match_twice_2idxs(0,0) },
    { STR("([abc])*d"), STR("abbbcd"), pm_match_2idxs(0,6), pm_match_2idxs(4,5) },
    { STR("([abc])*bcd"), STR("abcd"), pm_match_2idxs(0,4), pm_match_2idxs(0,1) },
    { STR("(a|b|c|d|e)f"), STR("ef"), pm_match_2idxs(0,2), pm_match_2idxs(0,1) },
    { STR("((a*|b))*"), STR("-"), pm_match_twice_2idxs(0,0) },
    { STR("(ab|cd)e"), STR("abcde"), pm_match_2idxs(2,5), pm_match_2idxs(2,4) },
    { STR("(a|b)c*d"), STR("abcd"), pm_match_2idxs(1,4), pm_match_2idxs(1,2) },
    { STR("(ab|ab*)bc"), STR("abc"), pm_match_2idxs(0,3), pm_match_2idxs(0,1) },
    { STR("a([bc]*)c*"), STR("abc"), pm_match_2idxs(0,3), pm_match_2idxs(1,3) },
    { STR("a([bc]*)(c*d)"), STR("abcd"), pm_match_2idxs(0,4), pm_match_2idxs(3,4) },
    { STR("a([bc]+)(c*d)"), STR("abcd"), pm_match_2idxs(0,4), pm_match_2idxs(3,4) },
    { STR("a([bc]*)(c+d)"), STR("abcd"), pm_match_2idxs(0,4), pm_match_2idxs(2,4) },
    { STR("(ab|a)b*c"), STR("abc"), pm_match_2idxs(0,3), pm_match_2idxs(0,2) },
    { STR("((a)(b)c)(d)"), STR("abcd"), pm_match_2idxs(0,4), pm_match_2idxs(3,4) },
    { STR("^a(bc+|b[eh])g|.h$"), STR("abh"), pm_match_twice_2idxs(1,3) },
    { STR("(bc+d$|ef*g.|h?i(j|k))"), STR("effgz"), pm_match_twice_2idxs(0,5) },
    { STR("(bc+d$|ef*g.|h?i(j|k))"), STR("ij"), pm_match_2idxs(0,2), pm_match_2idxs(1,2) },
    { STR("(bc+d$|ef*g.|h?i(j|k))"), STR("reffgz"), pm_match_twice_2idxs(1,6) },
    { STR("(((((((((a)))))))))"), STR("a"), pm_match_twice_2idxs(0,1) },
    { STR("(.*)c(.*)"), STR("abcde"), pm_match_2idxs(0,5), pm_match_2idxs(3,5) },
    { STR("a(bc)d"), STR("abcd"), pm_match_2idxs(0,4), pm_match_2idxs(1,3) },
    { STR("a+(b|c)*d+"), STR("aabcdd"), pm_match_2idxs(0,6), pm_match_2idxs(3,4) },
    { STR("^(.+)$"), STR("vivi"), pm_match_twice_2idxs(0,4) },
    { STR("^([^!.]+).att.com!(.+)$"), STR("gryphon.att.com!eby"), pm_match_2idxs(0,19), pm_match_2idxs(16,19) },
    { STR("^([^!]+!)?([^!]+)$"), STR("bar!bas"), pm_match_2idxs(0,7), pm_match_2idxs(4,7) },
    { STR("^([^!]+!)?([^!]+)$"), STR("foo!bas"), pm_match_2idxs(0,7), pm_match_2idxs(4,7) },
    { STR("^.+!([^!]+!)([^!]+)$"), STR("foo!bar!bas"), pm_match_2idxs(0,11), pm_match_2idxs(8,11) },
    { STR("((foo)|(bar))!bas"), STR("foo!bas"), pm_match_2idxs(0,7), pm_match_2idxs(0,3) },
    { STR("((foo)|bar)!bas"), STR("bar!bas"), pm_match_2idxs(0,7), pm_match_2idxs(0,3) },
    { STR("((foo)|bar)!bas"), STR("foo!bar!bas"), pm_match_2idxs(4,11), pm_match_2idxs(4,7) },
    { STR("((foo)|bar)!bas"), STR("foo!bas"), pm_match_2idxs(0,7), pm_match_2idxs(0,3) },
    { STR("(foo|(bar))!bas"), STR("bar!bas"), pm_match_2idxs(0,7), pm_match_2idxs(0,3) },
    { STR("(foo|(bar))!bas"), STR("foo!bar!bas"), pm_match_2idxs(4,11), pm_match_2idxs(4,7) },
    { STR("(foo|(bar))!bas"), STR("foo!bas"), pm_match_2idxs(0,7), pm_match_2idxs(0,3) },
    { STR("(foo|bar)!bas"), STR("bar!bas"), pm_match_2idxs(0,7), pm_match_2idxs(0,3) },
    { STR("(foo|bar)!bas"), STR("foo!bar!bas"), pm_match_2idxs(4,11), pm_match_2idxs(4,7) },
    { STR("(foo|bar)!bas"), STR("foo!bas"), pm_match_2idxs(0,7), pm_match_2idxs(0,3) },
    { STR("^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$"), STR("bar!bas"), pm_match_2idxs(0,7), pm_match_2idxs(4,7) },
    { STR("^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$"), STR("foo!bas"), pm_match_2idxs(0,7), pm_match_2idxs(4,7) },
    { STR("^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$"), STR("bar!bas"), pm_match_2idxs(0,7), pm_match_2idxs(0,4) },
    { STR("^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$"), STR("foo!bas"), pm_match_2idxs(0,7), pm_match_2idxs(0,4) },
    { STR(".*(/XXX).*"), STR("/XXX"), pm_match_twice_2idxs(0,4) },
    { STR(".*(\\\\XXX).*"), STR("\\XXX"), pm_match_twice_2idxs(0,4) },
};

global SuccTest regex_succ_subexpr_reps_tests[] = {
    { STR("((..)|(.))"), STR(""), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.))((..)|(.))"), STR(""), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.))((..)|(.))((..)|(.))"), STR(""), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.)){1}"), STR(""), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.)){2}"), STR(""), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.)){3}"), STR(""), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.))*"), STR(""), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.))((..)|(.))"), STR("a"), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.))((..)|(.))((..)|(.))"), STR("a"), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.)){2}"), STR("a"), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.)){3}"), STR("a"), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.))((..)|(.))((..)|(.))"), STR("aa"), pm_match_twice_2idxs(0,0) },
    { STR("((..)|(.)){3}"), STR("aa"), pm_match_twice_2idxs(0,0) },
    { STR("X(.?){0,}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){1,}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){2,}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){3,}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){4,}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){5,}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){6,}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){7,}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){8,}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){0,8}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){1,8}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){2,8}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){3,8}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){4,8}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){5,8}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){6,8}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){7,8}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("X(.?){8,8}Y"), STR("X1234567Y"), pm_match_twice_2idxs(0,9) },
    { STR("(a|ab|c|bcd){0,}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,1) },
    { STR("(a|ab|c|bcd){1,}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,1) },
    { STR("(a|ab|c|bcd){2,}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(a|ab|c|bcd){3,}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(a|ab|c|bcd){4,}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,0) },
    { STR("(a|ab|c|bcd){0,10}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,1) },
    { STR("(a|ab|c|bcd){1,10}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,1) },
    { STR("(a|ab|c|bcd){2,10}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(a|ab|c|bcd){3,10}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(a|ab|c|bcd){4,10}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,0) },
    { STR("(a|ab|c|bcd)*(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,1) },
    { STR("(a|ab|c|bcd)+(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,1) },
    { STR("(ab|a|c|bcd){0,}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(ab|a|c|bcd){1,}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(ab|a|c|bcd){2,}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(ab|a|c|bcd){3,}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(ab|a|c|bcd){4,}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,0) },
    { STR("(ab|a|c|bcd){0,10}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(ab|a|c|bcd){1,10}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(ab|a|c|bcd){2,10}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(ab|a|c|bcd){3,10}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(ab|a|c|bcd){4,10}(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,0) },
    { STR("(ab|a|c|bcd)*(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
    { STR("(ab|a|c|bcd)+(d*)"), STR("ababcd"), pm_match_twice_2idxs(0,6) },
};

global SuccTest regex_succ_unknown_assoc_tests[] = {
    { STR("(a|ab)(c|bcd)(d*)"), STR("abcd"), pm_match_twice_2idxs(0,4) },
    { STR("(a|ab)(bcd|c)(d*)"), STR("abcd"), pm_match_twice_2idxs(0,4) },
    { STR("(ab|a)(c|bcd)(d*)"), STR("abcd"), pm_match_twice_2idxs(0,4) },
    { STR("(ab|a)(bcd|c)(d*)"), STR("abcd"), pm_match_twice_2idxs(0,4) },
    { STR("(a*)(b|abc)(c*)"), STR("abc"), pm_match_twice_2idxs(0,3) },
    { STR("(a*)(abc|b)(c*)"), STR("abc"), pm_match_twice_2idxs(0,3) },
    { STR("(a|ab)(c|bcd)(d|.*)"), STR("abcd"), pm_match_twice_2idxs(0,4) },
    { STR("(a|ab)(bcd|c)(d|.*)"), STR("abcd"), pm_match_twice_2idxs(0,4) },
    { STR("(ab|a)(c|bcd)(d|.*)"), STR("abcd"), pm_match_twice_2idxs(0,4) },
    { STR("(ab|a)(bcd|c)(d|.*)"), STR("abcd"), pm_match_twice_2idxs(0,4) },
};

global SuccTest regex_succ_null_subexpr[] = {
    { STR("(a*)*"), STR("a"), pm_match_twice_2idxs(0,1) },
    { STR("(a*)*"), STR("x"), pm_match_twice_2idxs(0,0) },
    { STR("(a*)*"), STR("aaaaaa"), pm_match_twice_2idxs(0,6) },
    { STR("(a*)*"), STR("aaaaaax"), pm_match_twice_2idxs(0,6) },
    { STR("(a*)+"), STR("a"), pm_match_twice_2idxs(0,1) },
    { STR("(a+)*"), STR("a"), pm_match_twice_2idxs(0,1) },
    { STR("(a+)*"), STR("x"), pm_match_twice_2idxs(0,0) },
    { STR("(a+)+"), STR("a"), pm_match_twice_2idxs(0,1) },
    { STR("(a+)+"), STR("x"), pm_match_twice_2idxs(0,0) },
    { STR("([a]*)*"), STR("a"), pm_match_twice_2idxs(0,1) },
    { STR("([a]*)+"), STR("a"), pm_match_twice_2idxs(0,1) },
    { STR("([^b]*)*"), STR("a"), pm_match_twice_2idxs(0,1) },
    { STR("([^b]*)*"), STR("b"), pm_match_twice_2idxs(0,0) },
    { STR("([^b]*)*"), STR("aaaaaab"), pm_match_twice_2idxs(0,6) },
    { STR("([ab]*)*"), STR("a"), pm_match_twice_2idxs(0,1) },
    { STR("([ab]*)*"), STR("ababab"), pm_match_twice_2idxs(0,6) },
    { STR("([ab]*)*"), STR("bababa"), pm_match_twice_2idxs(0,6) },
    { STR("([ab]*)*"), STR("b"), pm_match_twice_2idxs(0,1) },
    { STR("([ab]*)*"), STR("bbbbbb"), pm_match_twice_2idxs(0,6) },
    { STR("([ab]*)*"), STR("aaaabcde"), pm_match_twice_2idxs(0,5) },
    { STR("([^a]*)*"), STR("b"), pm_match_twice_2idxs(0,1) },
    { STR("([^a]*)*"), STR("aaaaaa"), pm_match_twice_2idxs(0,0) },
    { STR("([^ab]*)*"), STR("ccccxx"), pm_match_twice_2idxs(0,6) },
    { STR("([^ab]*)*"), STR("ababab"), pm_match_twice_2idxs(0,0) },
    { STR("((z)+|a)*"), STR("zabcde"), pm_match_twice_2idxs(0,2) },
    { STR("a+?"), STR("aaaaaa"), pm_match_twice_2idxs(0,1) },
    { STR("(a)"), STR("aaa"), pm_match_twice_2idxs(0,1) },
    { STR("(a*?)"), STR("aaa"), pm_match_twice_2idxs(0,0) },
    { STR("(a)*?"), STR("aaa"), pm_match_twice_2idxs(0,0) },
    { STR("(a*?)*?"), STR("aaa"), pm_match_twice_2idxs(0,0) },
    { STR("(a*)*(x)"), STR("x"), pm_match_twice_2idxs(0,1) },
    { STR("(a*)*(x)"), STR("ax"), pm_match_twice_2idxs(0,2) },
    { STR("(a*)*(x)"), STR("axa"), pm_match_twice_2idxs(0,2) },
    { STR("(a*)+(x)"), STR("x"), pm_match_twice_2idxs(0,1) },
    { STR("(a*)+(x)"), STR("ax"), pm_match_twice_2idxs(0,2) },
    { STR("(a*)+(x)"), STR("axa"), pm_match_twice_2idxs(0,2) },
    { STR("(a*){2}(x)"), STR("x"), pm_match_twice_2idxs(0,1) },
    { STR("(a*){2}(x)"), STR("ax"), pm_match_twice_2idxs(0,2) },
    { STR("(a*){2}(x)"), STR("axa"), pm_match_twice_2idxs(0,2) },
};

// Tests taken from the D-lang's regex-tests
global SuccTest regex_succ_d_tests[] = {
    { STR("a\\b"), STR("a"), pm_match_twice(0, 1) },
    { STR("(a)b\\1"), STR("abaab"), pm_match_twice(0, 3) },
    { STR("()b\\1"), STR("aaab"), pm_match_twice(3, 1) },
    { STR("abc"), STR("abc"), pm_match_twice(0, 3) },
    { STR("abc"), STR("xbc"), pm_match_twice(0, 0) },
    { STR("abc"), STR("axc"), pm_match_twice(0, 0) },
    { STR("abc"), STR("abx"), pm_match_twice(0, 0) },
    { STR("abc"), STR("xabcy"), pm_match_twice(1, 3) },
    { STR("abc"), STR("ababc"), pm_match_twice(2, 3) },
    { STR("ab*c"), STR("abc"), pm_match_twice(0, 3) },
    { STR("ab*bc"), STR("abc"), pm_match_twice(0, 3) },
    { STR("ab*bc"), STR("abbc"), pm_match_twice(0, 4) },
    { STR("ab*bc"), STR("abbbbc"), pm_match_twice(0, 6) },
    { STR("ab+bc"), STR("abbc"), pm_match_twice(0, 4) },
    { STR("ab+bc"), STR("abc"), pm_match_twice(0, 0) },
    { STR("ab+bc"), STR("abq"), pm_match_twice(0, 0) },
    { STR("ab+bc"), STR("abbbbc"), pm_match_twice(0, 6) },
    { STR("ab?bc"), STR("abbc"), pm_match_twice(0, 4) },
    { STR("ab?bc"), STR("abc"), pm_match_twice(0, 3) },
    { STR("ab?bc"), STR("abbbbc"), pm_match_twice(0, 0) },
    { STR("ab?c"), STR("abc"), pm_match_twice(0, 3) },
    { STR("^abc$"), STR("abc"), pm_match_twice(0, 3) },
    { STR("^abc$"), STR("abcc"), pm_match_twice(0, 0) },
    { STR("^abc"), STR("abcc"), pm_match_twice(0, 3) },
    { STR("^abc$"), STR("aabc"), pm_match_twice(0, 0) },
    { STR("abc$"), STR("aabc"), pm_match_twice(1, 3) },
    { STR("^"), STR("abc"), pm_match_twice(0, 0) },
    { STR("$"), STR("abc"), pm_match_twice(0, 0) },
    { STR("a.c"), STR("abc"), pm_match_twice(0, 3) },
    { STR("a.c"), STR("axc"), pm_match_twice(0, 3) },
    { STR("a.*c"), STR("axyzc"), pm_match_twice(0, 5) },
    { STR("a.*c"), STR("axyzd"), pm_match_twice(0, 0) },
    { STR("a[bc]d"), STR("abc"), pm_match_twice(0, 0) },
    { STR("a[bc]d"), STR("abd"), pm_match_twice(0, 3) },
    { STR("a[b-d]e"), STR("abd"), pm_match_twice(0, 0) },
    { STR("a[b-d]e"), STR("ace"), pm_match_twice(0, 3) },
    { STR("a[b-d]"), STR("aac"), pm_match_twice(1, 2) },
    { STR("a[-b]"), STR("a-"), pm_match_twice(0, 2) },
    { STR("a[b-]"), STR("a-"), pm_match_twice(0, 2) },
    { STR("a]"), STR("a]"), pm_match_twice(0, 2) },
    { STR("a[\\]]b"), STR("a]b"), pm_match_twice(0, 3) },
    { STR("a[^bc]d"), STR("aed"), pm_match_twice(0, 3) },
    { STR("a[^bc]d"), STR("abd"), pm_match_twice(0, 0) },
    { STR("a[^-b]c"), STR("adc"), pm_match_twice(0, 3) },
    { STR("a[^-b]c"), STR("a-c"), pm_match_twice(0, 0) },
    { STR("a[^\\]b]c"), STR("adc"), pm_match_twice(0, 3) },
    { STR("ab|cd"), STR("abc"), pm_match_twice(0, 2) },
    { STR("ab|cd"), STR("abcd"), pm_match_twice(0, 2) },
    { STR("()ef"), STR("def"), pm_match_twice(-1, 3) },
    { STR("()*"), STR("-"), pm_match_twice(0, 1) },
    { STR("^*"), STR("-"), pm_match_twice(0, 1) },
    { STR("$*"), STR("-"), pm_match_twice(0, 1) },
    { STR("$b"), STR("b"), pm_match_twice(0, 0) },
    { STR("a\\(b"), STR("a(b"), pm_match_twice(-1, 4) },
    { STR("a\\(*b"), STR("ab"), pm_match_twice(0, 2) },
    { STR("a\\(*b"), STR("a((b"), pm_match_twice(0, 4) },
    { STR("a\\\\b"), STR("a\\b"), pm_match_twice(0, 3) },
    { STR("((a))"), STR("abc"), pm_match_twice(-1, 5) },
    { STR("(a)b(c)"), STR("abc"), pm_match_twice(-1, 7) },
    { STR("a+b+c"), STR("aabbabc"), pm_match_twice(4, 3) },
    { STR("a*?a"), STR("aa"), pm_match_twice(0, 1) },
    { STR("(a*)*"), STR("aaa"), pm_match_twice(-1, 1) },
    { STR("(a*)+"), STR("aaa"), pm_match_twice(-1, 1) },
    { STR("(a|)*"), STR("-"), pm_match_twice(0, 1) },
    { STR("(a*|b)*"), STR("aabb"), pm_match_twice(-1, 1) },
    { STR("(a|b)*"), STR("ab"), pm_match_twice(-1, 4) },
    { STR("(a+|b)*"), STR("ab"), pm_match_twice(-1, 4) },
    { STR("(a+|b)+"), STR("ab"), pm_match_twice(-1, 4) },
    { STR("(a+|b)?"), STR("ab"), pm_match_twice(-1, 3) },
    { STR("[^ab]*"), STR("cde"), pm_match_twice(0, 3) },
    { STR("(^)*"), STR("-"), pm_match_twice(0, 1) },
    { STR("(ab|)*"), STR("-"), pm_match_twice(0, 1) },
    { STR(""), STR("abc"), pm_match_twice(0, 0) },
    { STR("abc"), STR(""), pm_match_twice(0, 0) },
    { STR("a*"), STR(""), pm_match_twice(0, 0) },
    { STR("([abc])*d"), STR("abbbcd"), pm_match_twice(-1, 8) },
    { STR("([abc])*bcd"), STR("abcd"), pm_match_twice(-1, 6) },
    { STR("a|b|c|d|e"), STR("e"), pm_match_twice(0, 1) },
    { STR("(a|b|c|d|e)f"), STR("ef"), pm_match_twice(-1, 4) },
    { STR("((a*|b))*"), STR("aabb"), pm_match_twice(-1, 1) },
    { STR("abcd*efg"), STR("abcdefg"), pm_match_twice(0, 7) },
    { STR("ab*"), STR("xabyabbbz"), pm_match_twice(1, 2) },
    { STR("ab*"), STR("xayabbbz"), pm_match_twice(1, 1) },
    { STR("(ab|cd)e"), STR("abcde"), pm_match_twice(-1, 6) },
    { STR("[abhgefdc]ij"), STR("hij"), pm_match_twice(0, 3) },
    { STR("^(ab|cd)e"), STR("abcde"), pm_match_twice(0, 0) },
    { STR("(abc|)ef"), STR("abcdef"), pm_match_twice(-1, 3) },
    { STR("(a|b)c*d"), STR("abcd"), pm_match_twice(-1, 5) },
    { STR("(ab|ab*)bc"), STR("abc"), pm_match_twice(-1, 5) },
    { STR("a([bc]*)c*"), STR("abc"), pm_match_twice(-1, 6) },
    { STR("a([bc]*)(c*d)"), STR("abcd"), pm_match_twice(-1, 9) },
    { STR("a([bc]+)(c*d)"), STR("abcd"), pm_match_twice(-1, 9) },
    { STR("a([bc]*)(c+d)"), STR("abcd"), pm_match_twice(-1, 9) },
    { STR("a[bcd]*dcdcde"), STR("adcdcde"), pm_match_twice(0, 7) },
    { STR("a[bcd]+dcdcde"), STR("adcdcde"), pm_match_twice(0, 0) },
    { STR("(ab|a)b*c"), STR("abc"), pm_match_twice(-1, 6) },
    { STR("((a)(b)c)(d)"), STR("abcd"), pm_match_twice(-1, 9) },
    { STR("[a-zA-Z_][a-zA-Z0-9_]*"), STR("alpha"), pm_match_twice(0, 5) },
    { STR("^a(bc+|b[eh])g|.h$"), STR("abh"), pm_match_twice(-1, 3) },
    { STR("(bc+d$|ef*g.|h?i(j|k))"), STR("effgz"), pm_match_twice(-1, 12) },
    { STR("(bc+d$|ef*g.|h?i(j|k))"), STR("ij"), pm_match_twice(-1, 7) },
    { STR("(bc+d$|ef*g.|h?i(j|k))"), STR("effg"), pm_match_twice(0, 0) },
    { STR("(bc+d$|ef*g.|h?i(j|k))"), STR("bcdd"), pm_match_twice(0, 0) },
    { STR("(bc+d$|ef*g.|h?i(j|k))"), STR("reffgz"), pm_match_twice(-1, 12) },
    { STR("(((((((((a)))))))))"), STR("a"), pm_match_twice(0, 1) },
    { STR("multiple words of text"), STR("uh-uh"), pm_match_twice(0, 0) },
    { STR("multiple words"), STR("multiple words, yeah"), pm_match_twice(0, 14) },
    { STR("(.*)c(.*)"), STR("abcde"), pm_match_twice(-1, 11) },
    { STR("\\((.*), (.*)\\)"), STR("(a, b)"), pm_match_twice(-1, 6) },
    { STR("abcd"), STR("abcd"), pm_match_twice(-1, 12) },
    { STR("a(bc)d"), STR("abcd"), pm_match_twice(-1, 9) },
    { STR("[k]"), STR("ab"), pm_match_twice(0, 0) },
    { STR("[ -~]*"), STR("abc"), pm_match_twice(0, 3) },
    { STR("[ -~ -~]*"), STR("abc"), pm_match_twice(0, 3) },
    { STR("[ -~ -~ -~]*"), STR("abc"), pm_match_twice(0, 3) },
    { STR("[ -~ -~ -~ -~]*"), STR("abc"), pm_match_twice(0, 3) },
    { STR("[ -~ -~ -~ -~ -~]*"), STR("abc"), pm_match_twice(0, 3) },
    { STR("[ -~ -~ -~ -~ -~ -~]*"), STR("abc"), pm_match_twice(0, 3) },
    { STR("[ -~ -~ -~ -~ -~ -~ -~]*"), STR("abc"), pm_match_twice(0, 3) },
    { STR("a{2}"), STR("candy"), pm_match_twice(0, 0) },
    { STR("a{2}"), STR("caandy"), pm_match_twice(1, 2) },
    { STR("a{2}"), STR("caaandy"), pm_match_twice(1, 2) },
    { STR("a{2,}"), STR("candy"), pm_match_twice(0, 0) },
    { STR("a{2,}"), STR("caandy"), pm_match_twice(1, 2) },
    { STR("a{2,}"), STR("caaaaaandy"), pm_match_twice(1, 6) },
    { STR("a{1,3}"), STR("cndy"), pm_match_twice(0, 0) },
    { STR("a{1,3}"), STR("candy"), pm_match_twice(1, 1) },
    { STR("a{1,3}"), STR("caandy"), pm_match_twice(1, 2) },
    { STR("a{1,3}"), STR("caaaaaandy"), pm_match_twice(1, 3) },
    { STR("e?le?"), STR("angel"), pm_match_twice(3, 2) },
    { STR("e?le?"), STR("angle"), pm_match_twice(3, 2) },
    { STR("\\bn\\w"), STR("noonday"), pm_match_twice(0, 2) },
    { STR("\\wy\\b"), STR("possibly yesterday"), pm_match_twice(6, 2) },
    { STR("\\w\\Bn"), STR("noonday"), pm_match_twice(2, 2) },
    { STR("y\\B\\w"), STR("possibly yesterday"), pm_match_twice(9, 2) },
    { STR("\\cJ"), STR("abc\ndef"), pm_match_twice(3, 1) },
    { STR("\\d"), STR("B2 is"), pm_match_twice(1, 1) },
    { STR("\\D"), STR("B2 is"), pm_match_twice(0, 1) },
    { STR("\\s\\w*"), STR("foo bar"), pm_match_twice(3, 4) },
    { STR("\\S\\w*"), STR("foo bar"), pm_match_twice(0, 3) },
    { STR("abc"), STR("ababc"), pm_match_twice(2, 3) },
    { STR("apple(,)\\sorange\\1"), STR("apple, orange, cherry, peach"), pm_match_twice(0, 14) },
    { STR("(\\w+)\\s(\\w+)"), STR("John Smith"), pm_match_twice(-1, 11) },
    { STR("\\n\\f\\r\\t\\v"), STR("abc\n\f\r\t\vdef"), pm_match_twice(3, 5) },
    { STR(".*c"), STR("abcde"), pm_match_twice(0, 3) },
    { STR("^\\w+((;|=)\\w+)+$"), STR("some=host=tld"), pm_match_twice(-1, 20) },
    { STR("^\\w+((\\.|-)\\w+)+$"), STR("some.host.tld"), pm_match_twice(-1, 20) },
    { STR("q(a|b)*q"), STR("xxqababqyy"), pm_match_twice(-1, 8) },
    { STR("^(a)(b){0,1}(c*)"), STR("abcc"), pm_match_twice(-1, 6) },
    { STR("^(a)((b){0,1})(c*)"), STR("abcc"), pm_match_twice(-1, 5) },
    { STR("^(a)(b)?(c*)"), STR("abcc"), pm_match_twice(-1, 6) },
    { STR("^(a)((b)?)(c*)"), STR("abcc"), pm_match_twice(-1, 5) },
    { STR("^(a)(b){0,1}(c*)"), STR("acc"), pm_match_twice(-1, 5) },
    { STR("^(a)((b){0,1})(c*)"), STR("acc"), pm_match_twice(-1, 3) },
    { STR("^(a)(b)?(c*)"), STR("acc"), pm_match_twice(-1, 5) },
    { STR("^(a)((b)?)(c*)"), STR("acc"), pm_match_twice(-1, 3) },
    { STR("(?:ab){3}"), STR("_abababc"), pm_match_twice(-1, 7) },
    { STR("(?:a(?:x)?)+"), STR("aaxaxx"), pm_match_twice(-1, 7) },
    { STR("\\W\\w\\W"), STR("aa b!ca"), pm_match_twice(2, 3) },
//more repetitions:
    { STR("(?:a{2,4}b{1,3}){1,2}"), STR("aaabaaaabbb"), pm_match_twice(0, 11) },
    { STR("(?:a{2,4}b{1,3}){1,2}?"), STR("aaabaaaabbb"), pm_match_twice(0, 4) },
//groups:
    { STR("(abc)|(edf)|(xyz)"), STR("xyz"), pm_match_twice(-1, 5) },
    { STR("(?P<q>\\d+)/(?P<d>\\d+)"), STR("2/3"), pm_match_twice(-1, 3) },
//set operations:
    { STR("[a-z--d-f]"), STR(" dfa"), pm_match_twice(3, 1) },
    { STR("[abc[pq--acq]]{2}"), STR("bqpaca"), pm_match_twice(2, 2) },
    { STR("[a-z9&&abc0-9]{3}"), STR("z90a0abc"), pm_match_twice(5, 3) },
    { STR("[0-9a-f~~0-5a-z]{2}"), STR("g0a58x"), pm_match_twice(4, 2) },
    { STR("[abc[pq]xyz[rs]]{4}"), STR("cqxr"), pm_match_twice(0, 4) },
    { STR("[abcdf--[ab&&[bcd]][acd]]"), STR("abcdefgh"), pm_match_twice(5, 1) },
    { STR("[a-c||d-f]+"), STR("abcdef"), pm_match_twice(0, 6) },
    { STR("[a-f--a-c]+"), STR("abcdef"), pm_match_twice(3, 3) },
    { STR("[a-c&&b-f]+"), STR("abcdef"), pm_match_twice(1, 2) },
    { STR("[a-c~~b-f]+"), STR("abcdef"), pm_match_twice(0, 1) },
//unicode blocks & properties:
    { STR("[c-wф]фф"), STR("ффф"), pm_match_twice(0, 3) },
//case insensitive:
    { STR("^abcdEf$"), STR("AbCdEF"), pm_match_twice(0, 6) },
    { STR("Русский язык"), STR("рУсскИй ЯзЫк"), pm_match_twice(0, 12) },
    { STR("[adzУ-Я]{4}"), STR("DzюЯ"), pm_match_twice(0, 4) },
    { STR("(?:Dåb){3}"), STR("DåbDÅBdÅb"), pm_match_twice(0, 9) },
//escapes:
    { STR("[\\cJ\\cK\\cA-\\cD]{3}\\cQ"), STR("\x01\x0B\x0A\x11"), pm_match_twice(0, 4) },
    { STR("\r\n\v\t\f\\"), STR("\r\n\v\t\f\\"), pm_match_twice(0, 6) },
    { STR("\\w+\\S\\w+"), STR("ab7!44c"), pm_match_twice(0, 7) },
    { STR("\b\\w+\b"), STR(" abde4 "), pm_match_twice(1, 5) },
    { STR("\b\\w+\b"), STR(" abde4"), pm_match_twice(1, 5) },
    { STR("\b\\w+\b"), STR("abde4 "), pm_match_twice(0, 5) },
// ^, $, \b, \B, multiline :
    { STR("\r.*?$"), STR("abc\r\nxy"), pm_match_twice(3, 4) },
    { STR("^a$^b$"), STR("a\r\nb\n"), pm_match_twice(0, 0) },
    { STR("^a$\r\n^b$"), STR("a\r\nb\n"), pm_match_twice(0, 4) },
    { STR("^$"), STR("\r\n"), pm_match_twice(0, 0) },
    { STR("\b^."), STR("ab"), pm_match_twice(0, 1) },
    { STR("\\B^."), STR("ab"), pm_match_twice(0, 0) },
    { STR("^ab\\Bc\\B"), STR("\r\nabcd"), pm_match_twice(2, 3) },
    { STR("^.*$"), STR("12345678"), pm_match_twice(0, 8) },

// luckily obtained regression on incremental matching in backtracker
    { STR("^(?:(?:([0-9A-F]+)\\.\\.([0-9A-F]+)|([0-9A-F]+))\\s*;\\s*([^ ]*)\\s*#|# (?:\\w|_)+=((?:\\w|_)+))"), STR("0020  ; White_Space # "), pm_match_twice(-1, 6) },
//lookahead
    { STR("(foo.)(?=(bar))"), STR("foobar foodbar"), pm_match_twice(-1, 13) },
    { STR("\b(\\d+)[a-z](?=\1)"), STR("123a123"), pm_match_twice(-1, 8) },
    { STR("\\$(?!\\d{3})\\w+"), STR("$123 $abc"), pm_match_twice(5, 4) },
    { STR("(abc)(?=(ed(f))\3)"), STR("abcedff"), pm_match_twice(-1, 1) },
    { STR("\b[A-Za-z0-9.]+(?=(@(?!gmail)))"), STR("a@gmail,x@com"), pm_match_twice(-1, 3) },
    { STR("x()(abc)(?=(d)(e)(f)\2)"), STR("xabcdefabc"), pm_match_twice(0, 4) },
    { STR("x()(abc)(?=(d)(e)(f)()\3\4\5)"), STR("xabcdefdef"), pm_match_twice(0, 4) },
//lookback
    { STR("(?<=(ab))\\d"), STR("12ba3ab4"), pm_match_twice(-1, 1) },
    { STR("\\w(?<!\\d)\\w"), STR("123ab24"), pm_match_twice(3, 2) },
    { STR("(?<=Dåb)x\\w"), STR("DåbDÅBxdÅb"), pm_match_twice(6, 2) },
    { STR("(?<=(ab*c))x"), STR("abbbbcxac"), pm_match_twice(-1, 8) },
    { STR("(?<=(ab*?c))x"), STR("abbbbcxac"), pm_match_twice(-1, 8) },
    { STR("(?<=(a.*?c))x"), STR("ababbcxac"), pm_match_twice(-1, 6) },
    { STR("(?<=(a{2,4}b{1,3}))x"), STR("yyaaaabx"), pm_match_twice(-1, 7) },
    { STR("(?<=((?:a{2,4}b{1,3}){1,2}))x"), STR("aabbbaaaabx"), pm_match_twice(-1, 12) },
    { STR("(?<=((?:a{2,4}b{1,3}){1,2}?))x"), STR("aabbbaaaabx"), pm_match_twice(-1, 7) },
    { STR("(?<=(abc|def|aef))x"), STR("abcx"), pm_match_twice(-1, 5) },
    { STR("(?<=(abc|def|aef))x"), STR("aefx"), pm_match_twice(-1, 5) },
    { STR("(?<=(abc|dabc))(x)"), STR("dabcx"), pm_match_twice(-1, 7) },
    { STR("(?<=(|abc))x"), STR("dabcx"), pm_match_twice(-1, 2) },
    { STR("(?<=((ab|da)*))x"), STR("abdaabx"), pm_match_twice(-1, 11) },
    { STR("a(?<=(ba(?<=(aba)(?<=aaba))))"), STR("aabaa"), pm_match_twice(-1, 8) },
    { STR(".(?<!b)."), STR("bax"), pm_match_twice(1, 2) },
    { STR("(?<=b(?<!ab))."), STR("abbx"), pm_match_twice(3, 1) },
    { STR("(?<=\\.|[!?]+)X"), STR("Hey?!X"), pm_match_twice(5, 1) },
    { STR("(?<=\\.|[!?]+)a{3}"), STR(".Nope.aaaX"), pm_match_twice(6, 3) },
//mixed lookaround
    { STR("a(?<=a(?=b))b"), STR("ab"), pm_match_twice(0, 2) },
    { STR("a(?<=a(?!b))c"), STR("ac"), pm_match_twice(0, 2) },
    { STR("a(?i)bc"), STR("aBc"), pm_match_twice(0, 3) },
    { STR("a(?i)bc"), STR("Abc"), pm_match_twice(0, 0) },
    { STR("(?i)a(?-i)bc"), STR("aBcAbc"), pm_match_twice(3, 3) },
    { STR("(?s).(?-s)."), STR("\n\n\na"), pm_match_twice(2, 2) },
    { STR("(?m)^a(?-m)$"), STR("\na"), pm_match_twice(1, 1) },
};

global FailTest regex_fail_tests[] = {
    FAIL("*.c",    AIL_PM_ERR_INVALID_COUNT_QUALIFIER, 0),
    FAIL("$^",     AIL_PM_ERR_EARLY_END_MARKER, 0),
    FAIL("a[b-a]", AIL_PM_ERR_INVALID_RANGE, 4),
    FAIL("a[]b",   AIL_PM_ERR_INCOMPLETE_RANGE, 2),
    FAIL("a[",     AIL_PM_ERR_INCOMPLETE_RANGE, 2),
    FAIL("*a",     AIL_PM_ERR_INVALID_SPECIAL_CHAR, 0),
    FAIL("(*)b",   AIL_PM_ERR_INVALID_SPECIAL_CHAR, 1),
    FAIL("a\\",    AIL_PM_ERR_INCOMPLETE_ESCAPE, 2),
    // FAIL("abc)",   AIL_PM_ERR_INVALID_SPECIAL_CHAR, 0),
    // FAIL("(abc",   AIL_PM_ERR_INCOMPLETE_GROUP, 0),
    FAIL("a**",    AIL_PM_ERR_INVALID_SPECIAL_CHAR, 2),
    // FAIL(")(",     AIL_PM_ERR_INVALID_SPECIAL_CHAR, 0),
};


b32 pm_err_eq(AIL_PM_Err a, AIL_PM_Err b)
{
    return a.idx == b.idx && a.type == b.type;
}

b32 fail_tests(FailTest tests[], u32 count, AIL_PM_Exp_Type type, b32 verbose)
{
    char buffer[2048] = {0};
    for (u32 i = 0; i < count; i++) {
        AIL_Str pattern = tests[i].pattern;
        AIL_PM_Err err = tests[i].err;
        AIL_PM_Comp_Res cr = ail_pm_compile_str_a(pattern, type, ail_default_allocator);
        if (!cr.failed) {
            printf("\033[31mNo error thrown when compiling bad pattern: '%s'\033[0m\n", pattern.data);
            return false;
        }
        if (!pm_err_eq(err, cr.err)) {
            ail_pm_err_to_str(err, buffer, sizeof(buffer));
            printf("\033[31m'%s': Expected %s", pattern.data, buffer);
            ail_pm_err_to_str(cr.err, buffer, sizeof(buffer));
            printf(" - Received %s\033[0m\n", buffer);
            return false;
        }
        if (verbose) {
            ail_pm_err_to_str(cr.err, buffer, sizeof(buffer));
            printf("\033[32m'%s' -> %s\033[0m\n", pattern.data, buffer);
        }
    }
    return true;
}

b32 succ_tests(SuccTest tests[], u32 count, AIL_PM_Exp_Type type)
{
    char buffer[2048] = {0};
    for (u32 i = 0; i < count; i++) {
        SuccTest t = tests[i];
        AIL_PM_Comp_Res cr = ail_pm_compile_str_a(t.pattern, type, ail_default_allocator);
        if (cr.failed) {
            ail_pm_err_to_str(cr.err, buffer, ail_arrlen(buffer));
            printf("\033[31mFailed to compile '%s' (%s)\033[0m\n", t.pattern.data, buffer);
            return false;
        }

        AIL_PM_Match gm = ail_pm_match_greedy_str(cr.pattern, t.testStr);
        AIL_PM_Match lm = ail_pm_match_lazy_str(cr.pattern, t.testStr);
        if (!ail_pm_match_eq(gm, t.greedyRes) || !ail_pm_match_eq(lm, t.lazyRes)) {
            ail_pm_pattern_to_str(cr.pattern, buffer, sizeof(buffer));
            printf("\033[31mPattern: '%s' -> '%s':\033[0m\n", t.pattern.data, buffer);
            printf("\033[31mTest-String: '%s'\033[0m\n", t.testStr.data);
            printf("  Greedy: Expected: (%d, %d) - Received: (%d, %d)\n", t.greedyRes.idx, t.greedyRes.len, gm.idx, gm.len);
            printf("  Lazy:   Expected: (%d, %d) - Received: (%d, %d)\n", t.lazyRes.idx, t.lazyRes.len, lm.idx, lm.len);
            return false;
        }
    }
    return true;
}

int main(void)
{
    ail_default_allocator = ail_alloc_std;
    ail_pm_init(AIL_GB(1));
    if (succ_tests(regex_succ_basic_tests, ail_arrlen(regex_succ_basic_tests), AIL_PM_EXP_REGEX)) printf("\033[32mSuccessfully matched basic regex tests :)\033[0m\n");
    else printf("\033[31mFailed to match all basic regex tests :(\033[0m\n");
    if (succ_tests(regex_succ_question_tests, ail_arrlen(regex_succ_question_tests), AIL_PM_EXP_REGEX)) printf("\033[32mSuccessfully matched question regex tests :)\033[0m\n");
    else printf("\033[31mFailed to match all question regex tests :(\033[0m\n");
    if (succ_tests(regex_succ_group_tests, ail_arrlen(regex_succ_group_tests), AIL_PM_EXP_REGEX)) printf("\033[32mSuccessfully matched group regex tests :)\033[0m\n");
    else printf("\033[31mFailed to match all group regex tests :(\033[0m\n");
    if (succ_tests(regex_succ_or_tests, ail_arrlen(regex_succ_or_tests), AIL_PM_EXP_REGEX)) printf("\033[32mSuccessfully matched or regex tests :)\033[0m\n");
    else printf("\033[31mFailed to match all or regex tests :(\033[0m\n");
    if (succ_tests(regex_succ_subexpr_tests, ail_arrlen(regex_succ_subexpr_tests), AIL_PM_EXP_REGEX)) printf("\033[32mSuccessfully matched subexpr regex tests :)\033[0m\n");
    else printf("\033[31mFailed to match all subexpr regex tests :(\033[0m\n");
    if (succ_tests(regex_succ_null_subexpr, ail_arrlen(regex_succ_null_subexpr), AIL_PM_EXP_REGEX)) printf("\033[32mSuccessfully matched null-subexpr regex tests :)\033[0m\n");
    else printf("\033[31mFailed to match all null-subexpr regex tests :(\033[0m\n");
    if (succ_tests(regex_succ_subexpr_reps_tests, ail_arrlen(regex_succ_subexpr_reps_tests), AIL_PM_EXP_REGEX)) printf("\033[32mSuccessfully matched repition regex tests :)\033[0m\n");
    else printf("\033[31mFailed to match all subexpr repition regex tests :(\033[0m\n");
    if (succ_tests(regex_succ_unknown_assoc_tests, ail_arrlen(regex_succ_unknown_assoc_tests), AIL_PM_EXP_REGEX)) printf("\033[32mSuccessfully matched unknown-association regex tests :)\033[0m\n");
    else printf("\033[31mFailed to match all unknown-association regex tests :(\033[0m\n");
    if (succ_tests(regex_succ_d_tests, ail_arrlen(regex_succ_d_tests), AIL_PM_EXP_REGEX)) printf("\033[32mSuccessfully matched D-lang regex tests :)\033[0m\n");
    else printf("\033[31mFailed to match all D-lang regex tests :(\033[0m\n");

    if (fail_tests(regex_fail_tests, ail_arrlen(regex_fail_tests), AIL_PM_EXP_REGEX, false)) printf("\033[32mInvalid Regexs fail as expected :)\033[0m\n");
    else printf("\033[31mNot all invalid regexs failed to compile as expected :(\033[0m\n");

    if (succ_tests(glob_succ_tests, ail_arrlen(glob_succ_tests), AIL_PM_EXP_GLOB)) printf("\033[32mSuccessfully matched glob tests :)\033[0m\n");
    else printf("\033[31mFailed to match all glob tests :(\033[0m\n");
    if (fail_tests(glob_fail_tests, ail_arrlen(glob_fail_tests), AIL_PM_EXP_GLOB, false)) printf("\033[32mInvalid Globs fail as expected :)\033[0m\n");
    else printf("\033[31mNot all invalid globs failed to compile as expected :(\033[0m\n");

    ail_pm_deinit();
    return 0;
}
